print("\n")
print('----------**************************----------')
print('----------**************************----------')
print('----------Whelp I think this is code----------')
print('----------**************************----------')
print('----------**************************----------')
print("\n")
print('I wonder how many doors learning to code will open up for me...')
print('way more than...', 120*2/10, 'a month...\n')
print('"THEY" say it takes', ((99+5)*10%2+10000), 'hours of perfection')
print('some things in life are',89>88, 'but much more is', 77<33, '\n')
print('Python is WAY WAY WAY more than just a calculator\n')
x = float(input('how hot is your cpu "in celsius?"'))
print('Damn that is HOT!')
y = (x*1.8+32)
print('If you need that in fahrenheit it is:', y)
print('It should have a cooler, right?', 3+9==11)
print(3+9>21-20, "you can choose not to cool but that ain't kool")

